# Generated by Django 4.2.5 on 2023-10-08 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_problem_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="note",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="problem",
                to="api.note",
            ),
        ),
    ]
