# Generated by Django 4.2.5 on 2023-10-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_problemimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemimage",
            name="problem_image",
            field=models.ImageField(upload_to="app1/"),
        ),
    ]
