# Generated by Django 4.2.5 on 2023-10-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hirabun_alter_problem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem', to='api.note'),
        ),
    ]
