# Generated by Django 4.2.5 on 2023-10-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_problem_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirabun',
            name='order_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='order_num',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='order_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
