# Generated by Django 4.2.5 on 2023-10-05 07:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_hirabun_order_num_note_order_num_problem_order_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="ana",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2000), blank=True, size=None
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="mondaibun_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2000),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
