# Generated by Django 4.2.5 on 2023-10-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_problemimage_problem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemimage",
            name="problem_image",
            field=models.ImageField(max_length=1000000, upload_to=""),
        ),
    ]
