# Generated by Django 4.2.5 on 2023-10-14 06:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_delete_problemimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="mondaibun_list",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=2000), size=None
            ),
        ),
    ]
