// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxAOMCQs3hSvNoi_EQTu3glnLkIscFI7I',
    appId: '1:687667211195:web:c9b86faeb7f1a38fef329e',
    messagingSenderId: '687667211195',
    projectId: 'knowfill-7168e',
    authDomain: 'knowfill-7168e.firebaseapp.com',
    storageBucket: 'knowfill-7168e.appspot.com',
    measurementId: 'G-97Y4QZ60LD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG0Ws7zmXFRleppzlpxlqTSF237UbGNN8',
    appId: '1:687667211195:android:0bc9235508f7c50fef329e',
    messagingSenderId: '687667211195',
    projectId: 'knowfill-7168e',
    storageBucket: 'knowfill-7168e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD050JrNr7FSvp988z9enO0xoSrXSYJwL0',
    appId: '1:687667211195:ios:077f62dd6c8abce4ef329e',
    messagingSenderId: '687667211195',
    projectId: 'knowfill-7168e',
    storageBucket: 'knowfill-7168e.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD050JrNr7FSvp988z9enO0xoSrXSYJwL0',
    appId: '1:687667211195:ios:cd3a26707d9217c4ef329e',
    messagingSenderId: '687667211195',
    projectId: 'knowfill-7168e',
    storageBucket: 'knowfill-7168e.appspot.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
